# .github/release.yml
changelog:
  categories:
    - title: Major Updates
      labels:
        - major
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"