name: Dry Run Deploy
on:
  push:
    branches:
      - dev

jobs:
  dry-run-deploy:
    name: Dry Run Rsync to Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Setup Dashboard Changelog
        run: |
          DASHBOARD_CHANGELOG_PATH=wp-content/mu-plugins/dashboard-changelog
          FILE=${DASHBOARD_CHANGELOG_PATH}/vendor/erusev/parsedown/Parsedown.php
          if [ -f "$FILE" ]; then
            cd $DASHBOARD_CHANGELOG_PATH
            composer install --no-dev --no-progress
          fi

      - name: Dry Run Rsync
        run: |
          rsync -avzi --dry-run \
            --exclude='content' \         
            --exclude='node_modules' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='bin' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
