name: Run PHPCS
on:
  push:
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install SVN
        run: sudo apt-get install -y subversion
      - name: Install dependencies
        run: composer install
      - name: Run PHPCS
        run: composer phpcs