name: Deploy to Live
on:
  push:
    tags:
      - '*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.token }}
          source_ref: dev
          target_branch: main
          commit_message_template: '[Deploy] {github.event.head_commit.message}'
