name: Shellcheck
on: 
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer shellcheck
  test-dry-run:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_PATH: ${{ github.workspace }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Test dry run
        run: bash $WORKSPACE_PATH/bin/dry-run-release.sh /bin/bash