name: Shellcheck
on: 
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer shellcheck
  test-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Test dry run
        run: bash ${{ github.workspace }}/bin/dry-run-release.sh