name: Tag Release
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
    run: |
      git config --global user.name "GitHub Robot"
      git config --global user.email "bot@dev.null"
      bash ./bin/create_release.sh
