name: Tag Release
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from version.json
        run: echo "VERSION=$(jq -r .version ./version.json)" >> $GITHUB_ENV
      - name: Create Tag & Release
        run: |
          git config --global user.name "GitHub Robot"
          git config --global user.email "bot@dev.null"
          bash ${{ github.workspace }}/bin/create_release.sh --version $VERSION
      - name: Post-release update to dev
        run: |
          git config --global user.name "GitHub Robot"
          git config --global user.email "bot@dev.null"
          git checkout main && git pull
          git checkout dev && git pull
          git rebase main
          git push origin dev
