name: Tag Release
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get version from version.json
        run: echo "VERSION=$(jq -r .version ./version.json)" >> $GITHUB_ENV
      - name: Set Git Config
        run: |
          git config --global user.name "GitHub Robot"
          git config --global user.email "bot@dev.null"
      - name: Create Tag & Release
        run: |
          bash ${{ github.workspace }}/bin/create_release.sh --version $VERSION
      - name: Sync dev branch with main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || github.token }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/jazzsequence/jazzsequence.com.git
          git fetch origin
          git checkout dev
          git reset --hard origin/main
          git push --force origin dev
