name: Test scripts
on: 
  push:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer shellcheck
  test-dry-run:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_PATH: ${{ github.workspace }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Test dry run
        run: bash $WORKSPACE_PATH/bin/dry-run-release.sh /bin/bash
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh ${{ github.workspace }}/bin/bats        
      - name: Run Bats tests
        run: |
          cd ${{ github.workspace }}/bin/bats
          bin/bats ${{ github.workspace }}/bin/tests/*.bats